name: Check IEM
on:
  push:
  schedule:
    # UTC and picking a quiet processing time of day as some
    # autoplots like to timeout during the morning hours
    - cron: '37 4 * * *'
jobs:
  build-linux:
    name: Python (${{ matrix.PYTHON_VERSION }})
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.13"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    
    steps:
    - uses: actions/checkout@v4

    # Force Ipv4 usage
    #- name: Force Ipv4 to mesonet.agron
    #  run: |
    #    echo "129.186.90.1 mesonet.agron.iastate.edu" | sudo tee -a /etc/hosts

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    #- name: Setup upterm session
    #  uses: lhotari/action-upterm@v1
    #  with:
    #    limit-access-to-actor: true

    - name: Test with pytest
      run: |
        SERVICE=http://mesonet.agron.iastate.edu pytest -v -x
