name: Check IEM
on:
  push:
  schedule:
    # UTC and picking a quiet processing time of day as some
    # autoplots like to timeout during the morning hours
    - cron: '37 4 * * *'
jobs:
  build-linux:
    name: Python (${{ matrix.python-version }})
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.12"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    
    steps:
    - uses: actions/checkout@v4

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    - name: Test with pytest
      run: |
        pytest -n 8 -x
